### 张量的保存与加载

In [14]:
import torch

In [15]:
a = torch.rand(6)
a

tensor([0.3341, 0.9801, 0.9024, 0.9792, 0.8991, 0.8544])

In [16]:
torch.save(a, "models/tensor_a")
torch.load("models/tensor_a")

tensor([0.3341, 0.9801, 0.9024, 0.9792, 0.8991, 0.8544])

In [17]:
a = torch.rand(6)
b = torch.rand(6)
c = torch.rand(6)
[a,b,c]

[tensor([0.2068, 0.1687, 0.1243, 0.6716, 0.8314, 0.0648]),
 tensor([0.4220, 0.9659, 0.9497, 0.6557, 0.9215, 0.9614]),
 tensor([0.2321, 0.8685, 0.7852, 0.0403, 0.1495, 0.0018])]

In [18]:
torch.save([a,b,c],"models/tensor_abc")
torch.load("models/tensor_abc")

[tensor([0.2068, 0.1687, 0.1243, 0.6716, 0.8314, 0.0648]),
 tensor([0.4220, 0.9659, 0.9497, 0.6557, 0.9215, 0.9614]),
 tensor([0.2321, 0.8685, 0.7852, 0.0403, 0.1495, 0.0018])]

In [19]:
tensor_dict= {'a':a,'b':b,'c':c}
tensor_dict

{'a': tensor([0.2068, 0.1687, 0.1243, 0.6716, 0.8314, 0.0648]),
 'b': tensor([0.4220, 0.9659, 0.9497, 0.6557, 0.9215, 0.9614]),
 'c': tensor([0.2321, 0.8685, 0.7852, 0.0403, 0.1495, 0.0018])}

In [21]:
torch.save(tensor_dict,"models/tensor_dict_abc")
torch.load("models/tensor_dict_abc")

{'a': tensor([0.2068, 0.1687, 0.1243, 0.6716, 0.8314, 0.0648]),
 'b': tensor([0.4220, 0.9659, 0.9497, 0.6557, 0.9215, 0.9614]),
 'c': tensor([0.2321, 0.8685, 0.7852, 0.0403, 0.1495, 0.0018])}

### 模型的保存与加载

In [22]:
from torchvision import datasets
from torchvision import transforms
import torch.nn as nn 
import torch.optim as optim

class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.relu(out)
        out = self.fc3(out)
        return out
    
input_size = 28 * 28 
hidden_size = 512
num_classes = 10 

model = MLP(input_size, hidden_size, num_classes)

### 方式1

In [33]:
torch.save(model.state_dict(), "models/mlp_state_dict.pth")


model_load = MLP(input_size,hidden_size,num_classes)

# 调用load_state_dict方法 传入读取的参数
mlp_state_dict = torch.load("models/mlp_state_dict.pth")
model_load.load_state_dict(mlp_state_dict)

<All keys matched successfully>

In [34]:
mlp_state_dict

OrderedDict([('fc1.weight',
              tensor([[ 0.0206, -0.0345, -0.0221,  ..., -0.0337, -0.0355, -0.0160],
                      [ 0.0206, -0.0106, -0.0086,  ..., -0.0176, -0.0002, -0.0165],
                      [-0.0026,  0.0066, -0.0275,  ..., -0.0213, -0.0344,  0.0355],
                      ...,
                      [-0.0135, -0.0179,  0.0132,  ...,  0.0183,  0.0195,  0.0219],
                      [ 0.0245,  0.0243,  0.0177,  ...,  0.0153,  0.0224, -0.0353],
                      [-0.0168, -0.0053,  0.0267,  ..., -0.0211,  0.0225, -0.0102]])),
             ('fc1.bias',
              tensor([ 3.1718e-02, -1.4874e-02, -7.9082e-03, -3.6069e-03,  2.0391e-02,
                       2.1254e-02, -3.2543e-02,  1.6261e-02, -7.1722e-03, -1.9165e-02,
                      -2.1806e-03,  1.5472e-02,  3.1557e-02,  2.7973e-02,  1.1014e-02,
                       2.9658e-02, -3.1161e-02,  1.5704e-02,  1.0121e-02, -8.0777e-03,
                       2.4534e-02, -9.0364e-03,  4.4785e-03, -3.

In [35]:
model_load

MLP(
  (fc1): Linear(in_features=784, out_features=512, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=512, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=10, bias=True)
)

### 方式2

In [36]:
torch.save(model,"models/mlp_model.pth")
mlp_load = torch.load("models/mlp_model.pth")

In [28]:
mlp_load

MLP(
  (fc1): Linear(in_features=784, out_features=512, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=512, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=10, bias=True)
)

### 方式3

In [32]:
torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': loss,
            ...
            }, PATH)

SyntaxError: ':' expected after dictionary key (245471031.py, line 6)

In [ ]:
model = TheModelClass(*args, **kwargs)
optimizer = TheOptimizerClass(*args, **kwargs)

checkpoint = torch.load(PATH)
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']

model.eval()